#DBに関する設定
# デプロイにあたって
# localhost → database-1.c7nemfuoe0vm.us-east-2.rds.amazonaws.com
# username, password変更
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/task
    username: task
    password:

  sql:
    init:
      encoding: UTF-8
      mode: always

#GoogleOauth2.0に関する設定
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            # ↓本番環境(AWS内)ではコメントアウトを外す
            # redirect-uri: "https://git.heroku.com/mk-100588-task.git/login/oauth2/code/google"
            
            scope:
            - email
            - profile
            - openid
            - https://www.googleapis.com/auth/calendar

#Tomcatのポート番号
#AWS環境では8080なので以下コメントアウトする
server:
    port: 8080

#Log Level
logging:
  file:
    name: ./logs/tasktime.log
  level:
    '[com.example]': debug
    # '[org.springframework.web]': DEBUG
